### ISSUE TITLE
discussion src yaml format

### ISSUE THREAD

**Issue by officel** [officel/spelling-dictionary#20]
辞書の元になる入力ファイルの形式を、README.md から 辞書名.yaml に変更予定です。

yaml 形式の入力ファイルの構造について決めていきましょう

**Comment by ezaki** [comment]
現状readmeに書いているのは

- 参照元
- 辞書データ

くらいでしょうか。

```
title: Foo
description: dictionary description here.
see: example.com 
words:
  - foo
  - bar
```

これ以外に書くこと何がありますかね？

**Comment by officel** [comment]
そうですね。。。
本当はもっといろいろ書きたいというか、辞書ファイルから理解をスタートさせてもいいかなと思っているので、wordsの中はディクショナリになってるほうがいいかなと思ったりします。
あとは、採用しなかった語句についてもメモしておきたいと思っています。
https://github.com/officel/spelling-dictionary/tree/master/dictionaries/plantuml
とか
https://github.com/officel/spelling-dictionary/tree/master/dictionaries/azure
とかですね。

表現しようと思っている語句をリストしていると、表現しようと思っていない語句もTYPOになっている（Xamarinとかそうです）のがあって、ここのリストには入れないよ、これはこういうものだよ、参照はここだよ、ということが書けるといいなぁと思います。

この時、（前述のREADMEのように）入れるリストと入れないリストに分けるのと、同一のリストにしておいてフラグにするのとどっちがいいか、は悩みます。

```
title: Foo
description: dictionary description here.
see: example.com 
notes:
  - memo here
  - relation link, etc...
words:
  - word: foo
    desc: foo's description
    see: foo's URL
    include: true
  - word: bar
    include: false
```

こんな感じですかね。

words を include-words と exclude-words みたいに二つのリストに分けるのとどっちがいいでしょう？
できれば不採用な語句は切り捨てる（書かない）は避けたい。。。

**Comment by ezaki** [comment]
なるほど。理解しました。

採用しなかった語句については確かにその通りですね。
入っていない語句について同じ議論を繰り返す原因になりますし。

include, exclude についてはリストを分ける方が良いと思います。
辞書として登録されている、いないについては最も重要な点だと思いますので、
フラグにすると見通しが悪くなりそう（人が見たときに各々の単語についてinclude,excludeのどちらかを判断する必要がある）です。
多分フラグの切り替えが必要になることも早々なさそうですし、分けちゃっていいかと。

各wordのdesc, seeなどについては （ご提示の通り）optional 扱いとしておいた方が良さそうですね。

一点気になる所としては、notesについては想定される内容で最初から分割しておいた方がいいかと思います。

```
title: Foo
description: dictionary description here.
see: example.com 
link: relation link (optional)
words:
  - word: foo
    desc: foo's description (optional)
    see: foo's URL (optional)
exclude-words: (optional)
  - word: bar
    desc: why exclude it
```

こんな感じですかね？

**Comment by officel** [comment]
そうですね。リストは分けたほうがよさそうですね。

入れない理由を書いていても、その語句が他で入れられるとは限らないので、場合によってはフラグを自分で立てることでコントロールするのに楽かなとも思ったのですが。。。
結局レアケースなら重要なほうを優先したほうがよさそうです。

note に関しては、ノードそのものをアンタッチャブル扱いでいいかなと考えています。
結構メモ魔なので関連する項目等々いろいろ書くかなって。。。

**Comment by ezaki** [comment]
noteの名前だと何でも書ける反面、何を書いて良いかわからないようになりがちかと思うんですよね。
gitのコミットコメントやJavaDocのように、descriptionの一行目に大まかな概要、
二行目以降に細かな内容（今回のnoteに当たる部分）のような形ではいかがですか？

**Comment by officel** [comment]
そうですね！別にノードを取るよりそのほうがわかりやすいし楽そうですね。
それがいいと思います！

**Comment by ezaki** [comment]
そうなるとこんな感じですかね？

```
title: Foo
description:  |
    dictionary simple description here.
        (if you write ditail, create empty row here.)
    if you want to write detail, please write here.
    you can write multi-line description.
see: example.com 
link: relation link (optional)
words:
  - word: foo
    description: foo's description (optional)
    see: foo's URL (optional)
exclude-words: (optional)
  - word: bar
    description: why exclude it
```
